name: Update WakaTime Metrics

on:
    schedule:
        - cron: '0 16 * * *' # 每天台北時間 00:00
    workflow_dispatch: # 支援手動觸發

jobs:
    update-readme:
        name: Update README with WakaTime Metrics
        runs-on: ubuntu-latest
        steps:
            - uses: anmol098/waka-readme-stats@master
              with:
                WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
                SHOW_SHORT_INFO: True
                SHOW_TOTAL_CODE_TIME: True
                SHOW_UPDATED_DATE: True
                SHOW_LANGUAGE: True
                SHOW_LINES_OF_CODE: True
                SHOW_DAYS_OF_WEEK: True
                SHOW_COMMIT: True
                SHOW_LOC_CHART: False
                SHOW_PROFILE_VIEWS: False
                SHOW_OS: False
                SHOW_EDITORS: False
                SHOW_PROJECTS: False
                SHOW_LANGUAGE_PER_REPO: False
                UPDATED_DATE_FORMAT: "%Y/%m/%d %H:%M:%S"